homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/Chicago
  elevation: 181
  internal_url: !secret internal_url
  external_url: !secret external_url
  packages: !include_dir_named packages
  customize:
    sensor.holidays_calendar:
      icon: mdi:calendar
      friendly_name: Upcoming Holiday

# Text to speech
tts:
  - platform: google_translate
lovelace:
  mode: yaml
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

cloud:
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend: !include frontend.yaml
