#!/usr/bin/env bash
set -e

ssh homeassistant "ha snapshots new"

rsync -naptlzv \
  --backup \
  --backup-dir="/root/.backup" \
  --verbose \
  secrets.yaml \
  homeassistant:/root/config/secrets.yaml
